apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - env:                   
            - name: MYSQL_DB     
              value: node_db     
            - name: MYSQL_HOST   
              value: mysql-app   
            - name: MYSQL_PASS   
              value: password    
            - name: MYSQL_USER   
              value: admin       
          name: nodejs-app
          image: nodejs-app:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: 
  selector:
    app: node
  ports:
    - port: 8005 # expose the service on internal port 80
      targetPort: 8005 # our NodeJS app listens on port 3000
