apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service 
          servicePort: http
      - path: /api
        backend:
          serviceName: frontend-service 
          servicePort: http
